name: Find licences
on:
  release:
    types: [published]

jobs:
  scan:
    name: Create and upload SBOM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: github-actions
    steps:
      - uses: actions/checkout@v2
        name: Create SBOM
      - name: install dependencies
        run: npm ci
      - uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{secrets.fossaApiKey}}
